# ( cd themes && git clone git@github.com:pdevty/material-design.git )
theme = "material-design"
baseurl = "https://blog.pchudzik.com"
languageCode = "en-us"
title = "tech_gibberish"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "blog-pchudzik-com"
copyright = "© 2018 Copyright Paweł Chudzik"

pygmentsstyle = "manni"

[params]
  description = "by Paweł Chudzik"
  github = "pchudzik"
  headerCover = "images/header.jpeg"
  footerCover = "images/footer.jpeg"
  linkedin = "pawel-chudzik"
  googleAnalyticsUserID = "UA-85832534-1"

[permalinks]
  post = "/:year:month/:filename"
