# ( cd themes && git clone git@github.com:pdevty/material-design.git )
theme = "material-design"
baseurl = "https://blog.pchudzik.com"
languageCode = "en-us"
title = "tech gibberish"
MetaDataFormat = "toml"
paginate = 6 # To specify a multiple of 3
disqusShortname = "blog-pchudzik-com"
copyright = "© 2017 Copyright Paweł Chudzik"

[params]
  description = "by Paweł Chudzik"
  github = "pchudzik"
  headerCover = "images/header.jpeg"
  footerCover = "images/footer.jpeg"
  linkedin = "paweł-chudzik-752483130"
  googleAnalyticsUserID = "UA-85832534-1"

[permalinks]
  post = "/:year:month/:filename"
